using System;
using System.Collections.Generic;

#nullable disable

namespace Matbaa_Erp.Entities
{
    public partial class TblMaliyet
    {
        public long Maliyetkodu { get; set; }
        public string Firmakod { get; set; }
        public double Maliyeten { get; set; }
        public double Maliyetboy { get; set; }
        public double Maliyetadet { get; set; }
        public byte Maliyetrenk { get; set; }
        public int Mamultipkod { get; set; }
        public string Slevetip { get; set; }
        public bool BicakVar { get; set; }
        public bool Yenibicak { get; set; }
        public bool BaskiVar { get; set; }
        public byte Renk { get; set; }
        public string Makinakodu { get; set; }
        public string Makinakodub { get; set; }
        public short Bicakek { get; set; }
        public short Malzemeek { get; set; }
        public short Makinaek { get; set; }
        public string Bicakkodu { get; set; }
        public double Tekebadboy { get; set; }
        public double Tekebaden { get; set; }
        public double Tekebadyukseklik { get; set; }
        public short Yyadet { get; set; }
        public double Aabosluk { get; set; }
        public double Yybosluk { get; set; }
        public short Yybitisikadet { get; set; }
        public short Musteriyyadet { get; set; }
        public double Lf { get; set; }
        public double Cl { get; set; }
        public double Netenverimi { get; set; }
        public double Enverimi { get; set; }
        public bool BicakmasrafEkle { get; set; }
        public double Bicakmasraf { get; set; }
        public bool KlisemasrafEkle { get; set; }
        public double Klisetutar { get; set; }
        public string Malzemecinsi { get; set; }
        public bool MalzemecinsiEkle { get; set; }
        public double Malzemefiyat { get; set; }
        public double Gramaj { get; set; }
        public double Kalinlik { get; set; }
        public double Yogunluk { get; set; }
        public string Malzemecinsi2 { get; set; }
        public bool MalzemecinsiEkle2 { get; set; }
        public double Malzemefiyat2 { get; set; }
        public double Gramaj2 { get; set; }
        public bool VadeEkle { get; set; }
        public short Vade { get; set; }
        public float Vadevalor { get; set; }
        public bool BoyayogunluguEkle { get; set; }
        public string Boyayogunluk { get; set; }
        public double Boyafiyat { get; set; }
        public bool LaminasyoncinsiEkle { get; set; }
        public string Laminasyonadi { get; set; }
        public double Genelgidereur { get; set; }
        public double Genelgider { get; set; }
        public double Yonetimgideri { get; set; }
        public string Urunadi { get; set; }
        public string Urunkod { get; set; }
        public string Ozelbilgi { get; set; }
        public string Onayagonderen { get; set; }
        public DateTime? Onayagondertarih { get; set; }
        public string KontrolMaliyet { get; set; }
        public bool DurumKontrol { get; set; }
        public string Teklifbirimi { get; set; }
        public string Birimkod { get; set; }
        public bool Baskibicakayri { get; set; }
        public string Bicaktipkod { get; set; }
        public bool Adettakim { get; set; }
        public short Takimmiktar { get; set; }
        public string Rulobirim { get; set; }
        public bool Adettakim2 { get; set; }
        public short Takimmiktar2 { get; set; }
        public short Takimuretimmiktar { get; set; }
        public double Depolama { get; set; }
        public string Uruntipkod { get; set; }
        public string Dovizkod { get; set; }
        public bool Ribon { get; set; }
        public string Musterikod { get; set; }
        public string Onayliyan { get; set; }
        public DateTime? Onaytarih { get; set; }
        public double Uruneken { get; set; }
        public double Maliyeteken { get; set; }
        public float Baglamaucreti { get; set; }
        public string Baglamaparabirimi { get; set; }
        public bool Baglamafaturaet { get; set; }
        public string Urunbirimtip { get; set; }
        public double Alannet { get; set; }
        public double Alan { get; set; }
        public double Agirliknet { get; set; }
        public double Agirlik { get; set; }
        public string Tipi { get; set; }
        public string Hammaddefiyatbirimi { get; set; }
        public string Uygulamasekli { get; set; }
        public string Yaldiz { get; set; }
        public string Holtmelt { get; set; }
        public string Perfore { get; set; }
        public string Laminasyon { get; set; }
        public string Acan { get; set; }
        public string Rpt { get; set; }
        public byte Cesit { get; set; }
        public byte Montaj { get; set; }
        public double Yapistirmapayi { get; set; }
        public bool Devamlilik { get; set; }
        public bool Ortfiyatvar { get; set; }
        public DateTime? Fiyattarih { get; set; }
        public double Eurokur { get; set; }
        public double Dolarkur { get; set; }
        public double Eurobarite { get; set; }
        public double Sabitkur { get; set; }
        public double Genelgideryuzde { get; set; }
        public string Ek1 { get; set; }
        public string Ek2 { get; set; }
        public string Ek3 { get; set; }
        public string Ek4 { get; set; }
        public string Ek5 { get; set; }
        public string Ek6 { get; set; }
        public string Olusturanadisoyadi { get; set; }
        public DateTime Olusturmatarihi { get; set; }
    }
}
