using System;
using System.Collections.Generic;

#nullable disable

namespace Matbaa_Erp.Entities
{
    public partial class TblSipari
    {
        public int Siparisno { get; set; }
        public string Urunkod { get; set; }
        public string Revizyonkod { get; set; }
        public double Siparismiktar { get; set; }
        public string Birimkod { get; set; }
        public DateTime Siparistarih { get; set; }
        public string Siparisbirim { get; set; }
        public double Siparisfiyat { get; set; }
        public string Dovizkod { get; set; }
        public int Maliyetkodu { get; set; }
        public string Firmakod { get; set; }
        public short FirmId { get; set; }
        public double Kdv { get; set; }
        public string Kisikod { get; set; }
        public string Ozelbilgi { get; set; }
        public double Bicakfiyat { get; set; }
        public string Bdovizkod { get; set; }
        public string Bbirim { get; set; }
        public double Klisefiyat { get; set; }
        public string Kdovizkod { get; set; }
        public short Kliseadet { get; set; }
        public bool Bfaturaet { get; set; }
        public bool Bfaturaedildi { get; set; }
        public bool Kfaturaet { get; set; }
        public bool Kfaturaedildi { get; set; }
        public double Uygulamamiktar { get; set; }
        public bool KontrolKapat { get; set; }
        public DateTime? Kapattarih { get; set; }
        public bool KontrolDepo { get; set; }
        public bool KontrolKapat2 { get; set; }
        public double Toplamalan { get; set; }
        public double Toplamagirlik { get; set; }
        public double Toplamadet { get; set; }
        public double Toplamteslimmiktar { get; set; }
        public string Personelkodu { get; set; }
        public string Temsilci { get; set; }
        public bool Imalattakip { get; set; }
        public int Tramyogunlugu { get; set; }
        public double Gelirtutar { get; set; }
        public double Gelirtutarklise { get; set; }
        public double Gelirtutarbicak { get; set; }
        public double Gidertutar { get; set; }
        public double Gidertutarkur { get; set; }
        public double Maliyetadet { get; set; }
        public double Toplamteslim { get; set; }
        public DateTime? Muhtemeltarih { get; set; }
        public DateTime? Planlanantarih { get; set; }
        public bool Depodan { get; set; }
        public bool Ilkdefa { get; set; }
        public string Ilkdefauy { get; set; }
        public bool Revizyonvar { get; set; }
        public bool Eskifilmat { get; set; }
        public bool Revizyonfilmdegil { get; set; }
        public string Revizyonnot { get; set; }
        public string Irsaliyenot { get; set; }
        public string Faturanot { get; set; }
        public string Musterisano { get; set; }
        public string Onayadres { get; set; }
        public int Oncekilot { get; set; }
        public bool Iptal { get; set; }
        public bool Prova { get; set; }
        public double Globalfiyat { get; set; }
        public string Yeniurun { get; set; }
        public string Urunacildi { get; set; }
        public double Satistltutar { get; set; }
        public bool Bedelsiz { get; set; }
        public byte Satistipi { get; set; }
        public string Testtipi { get; set; }
        public short Numuneadet { get; set; }
        public double Urunalan { get; set; }
        public double Sabitkur { get; set; }
        public string Grafikpersonel { get; set; }
        public string Grafikonay { get; set; }
        public string Kardes { get; set; }
        public string Siparisurunadi { get; set; }
        public string Siparismusterikod { get; set; }
        public double Siparistekebadboy { get; set; }
        public double Siparistekebaden { get; set; }
        public double Siparistekebadyukseklik { get; set; }
        public short Siparisyyadet { get; set; }
        public double Siparisaabosluk { get; set; }
        public double Siparisyybosluk { get; set; }
        public short Siparisyybitisikadet { get; set; }
        public double Siparisbaskiaabosluk { get; set; }
        public double Siparislf { get; set; }
        public double Siparisyapistirmapayi { get; set; }
        public double Sipariscl { get; set; }
        public string Siparisuygulamasekli { get; set; }
        public string Siparisholtmelt { get; set; }
        public string Siparisperfore { get; set; }
        public string Siparisbicakkodu { get; set; }
        public string Siparisurunnot { get; set; }
        public bool Siparisadettakim { get; set; }
        public short Siparistakimmiktar { get; set; }
        public string Siparisrulobirim { get; set; }
        public bool Siparisadettakim2 { get; set; }
        public short Siparistakimmiktar2 { get; set; }
        public double Siparisuruneken { get; set; }
        public bool Siparisdevamlilik { get; set; }
        public string Siparisarsivno { get; set; }
        public string Siparisboyayogunluk { get; set; }
        public string Sipariskliseno { get; set; }
        public double Onaydakibakiye { get; set; }
        public string Bakiyedovizkod { get; set; }
        public double Onaydakirisk { get; set; }
        public string Riskdovizkod { get; set; }
        public string Muhasebeonay { get; set; }
        public string Muhasebeonaylayan { get; set; }
        public DateTime? Muhasebeonaytarih { get; set; }
        public string Yonetimonay { get; set; }
        public string Yonetimonaylayan { get; set; }
        public DateTime? Yonetimonaytarih { get; set; }
        public string Yonetimonay2 { get; set; }
        public string Yonetimonaylayan2 { get; set; }
        public DateTime? Yonetimonaytarih2 { get; set; }
        public string Bicakdurum { get; set; }
        public string Klisedurum { get; set; }
        public string Malzemedurum { get; set; }
        public DateTime? Planlamatermintarihi { get; set; }
        public string Carikod { get; set; }
        public DateTime? Planlamakabultarihi { get; set; }
        public double Iskontoyuzde { get; set; }
        public DateTime? Kapanistarihi { get; set; }
        public string Olusturanadisoyadi { get; set; }
        public DateTime Olusturmatarihi { get; set; }
    }
}
